name: Run WPQR Notebook

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC
  workflow_dispatch:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or '3.x' for always-latest Python 3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute wpqr_logic.ipynb --output output.ipynb

      - name: Upload output notebook
        uses: actions/upload-artifact@v4
        with:
          name: wpqr-output
          path: output.ipynb

